In [2]:
import pandas as pd
import numpy as np
import math

## 1. Check qls.csv

In [3]:
face = pd.read_csv('./penstate_data/download/qls.csv')
face

ID        V1        V2        V3        V4        V5        V6  \
0     140012  1.142104  0.302941 -0.710802  1.142799  0.271451 -0.716142   
1     140017  1.149520  0.300287 -0.684552  1.148626  0.268567 -0.690915   
2     140018  1.168593  0.277356 -0.688271  1.170581  0.246254 -0.692626   
3     140019  1.093736  0.279753 -0.715639  1.095212  0.248028 -0.721778   
4     140020  1.204328  0.298106 -0.654091  1.205471  0.267064 -0.659410   
...      ...       ...       ...       ...       ...       ...       ...   
1073  143771  1.186773  0.284742 -0.665635  1.188940  0.253130 -0.670528   
1074  143772  1.141765  0.284188 -0.667118  1.141683  0.252735 -0.672775   
1075  143773  1.185780  0.271971 -0.629181  1.188293  0.240712 -0.635866   
1076  143774  1.194996  0.282105 -0.638625  1.194881  0.250626 -0.643812   
1077  143775  1.227406  0.284488 -0.671805  1.227768  0.252590 -0.677953   

            V7        V8        V9  ...    V20361    V20362    V20363  \
0     1.140874  0.240170 -0.719405  ... -0.735470 -1.137672  0.145935   
1     1.144041  0.237009 -0.695634  ... -0.709256 -1.128049  0.145643   
2     1.170916  0.215361 -0.694578  ... -0.700240 -1.167515  0.128537   
3     1.094825  0.215972 -0.725795  ... -0.734093 -1.088197  0.133849   
4     1.204657  0.235932 -0.662561  ... -0.670984 -1.197001  0.144216   
...        ...       ...       ...  ...       ...       ...       ...   
1073  1.188923  0.221499 -0.673963  ... -0.691106 -1.186213  0.131858   
1074  1.139000  0.220820 -0.676174  ... -0.684951 -1.129100  0.131657   
1075  1.190887  0.208437 -0.640092  ... -0.649076 -1.192142  0.108672   
1076  1.192110  0.218945 -0.647304  ... -0.662508 -1.185380  0.129357   
1077  1.226260  0.219940 -0.681828  ... -0.689045 -1.217487  0.126365   

        V20364    V20365    V20366    V20367    V20368    V20369    V20370  
0    -0.730931 -1.141756  0.175892 -0.724656 -1.144403  0.206969 -0.720106  
1    -0.704599 -1.134815  0.176807 -0.698365 -1.139156  0.208658 -0.693825  
2    -0.697338 -1.169538  0.158299 -0.693222 -1.170934  0.189161 -0.690173  
3    -0.730142 -1.090463  0.164519 -0.725203 -1.092341  0.195576 -0.721081  
4    -0.666816 -1.199955  0.174402 -0.661598 -1.202177  0.205162 -0.657615  
...        ...       ...       ...       ...       ...       ...       ...  
1073 -0.686316 -1.190137  0.162746 -0.680038 -1.192317  0.194252 -0.676025  
1074 -0.681118 -1.132830  0.162250 -0.676173 -1.135421  0.193329 -0.672207  
1075 -0.645450 -1.189774  0.140396 -0.640465 -1.189483  0.171503 -0.635856  
1076 -0.658562 -1.189708  0.159697 -0.653072 -1.192598  0.190586 -0.649308  
1077 -0.685735 -1.219491  0.158065 -0.681150 -1.221615  0.189674 -0.677058  

[1078 rows x 20371 columns]

In [4]:
num_cols = face.shape[1] - 1
print("Total number of cordinate column: ", num_cols)

num_cordinate_col = num_cols//3
print("Number of a single cordinate column (x/y/z): ", num_cordinate_col) 

np_face = np.array(face)

Total number of cordinate column:  20370
Number of a single cordinate column (x/y/z):  6790


### 1.1 Test

In [8]:
face.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1078 entries, 0 to 1077
Columns: 20371 entries, ID to V20370
dtypes: float64(20370), int64(1)
memory usage: 167.5 MB


In [4]:
face.values.shape

(1078, 20371)

## 2. Choose index from face dataframe(qls.csv)

In [5]:
# Pick 65 points on the face
face_indices = [2570, 2569, 2564, 3675, 2582,
                 1445, 3848, 1427, 1432, 1433,
                 2428, 2451, 2495, 2471, 3638, 2276, 2355, 2359,
                 3835, 1292, 1344, 1216, 1154, 999, 991, 4046,
                 3704, 3553, 3561, 3501, 3564,
                 2747, 1613, 1392, 3527, 471, 480, 1611,
                 3797, 2864, 2811, 3543, 1694, 1749,
                 3920, 2881, 2905, 1802, 1774, 3503,
                 3515, 3502, 3401, 3399, 3393,
                 3385, 1962, 3381, 3063, 3505,
                 3595, 3581, 3577, 2023, 567]

In [6]:
# Different AM chosen
measurement_info = [
            # 0 - 24
            ['dist', 10, 14],
            ['dist', 18, 22],
            ['dist', 14, 18],
            ['dist', 10, 22],
            ['dist', 4, 5],
            ['dist', 0, 9],
            ['dist', 2, 7],
            ['dist', 58, 60],
            ['dist', 57, 61],
            ['dist', 56, 62],
            ['dist', 55, 63],
            ['dist', 54, 64],
            ['dist', 31, 37], ##
            ['dist', 32, 36], ##
            ['dist', 33, 35], #
            ['dist', 48, 46], ##
            ['dist', 40, 42], ##
            ['dist', 54, 53],
            ['dist', 53, 64],
            ['dist', 38, 44],
            ['dist', 48, 46], ##
            ['dist', 39, 43], #
            ['dist', 41, 47], #
            ['dist', 12, 16],
            ['dist', 20, 24],

            # 25 - 49
            ['dist', 59, 27],
            ['dist', 59, 30],
            ['dist', 59, 34],
            ['dist', 59, 50],
            ['dist', 59, 51],
            ['dist', 59, 53],
            ['dist', 27, 30],
            ['dist', 26, 50],
            ['dist', 30, 34],
            ['dist', 30, 51],
            ['dist', 30, 52],
            ['dist', 30, 53],
            ['dist', 34, 50],
            ['dist', 41, 47], #
            ['dist', 51, 52],
            ['dist', 52, 53],
            ['dist', 50, 53],
            ['dist', 54, 55],
            ['dist', 55, 56],
            ['dist', 56, 57],
            ['dist', 57, 58],
            ['dist', 60, 61],
            ['dist', 61, 62],
            ['dist', 62, 63],
            ['dist', 63, 64],

            # 50 - 63
            ['prop', 31, 37, 27, 30], ##
            ['prop', 32, 36, 27, 30], ##
            ['prop', 57, 61, 27, 30],
            ['prop', 56, 62, 27, 30],
            ['prop', 55, 63, 27, 30],
            ['prop', 54, 64, 27, 30],
            ['prop', 38, 44, 27, 30],
            ['prop', 31, 37, 59, 53], ##
            ['prop', 32, 36, 59, 53], #
            ['prop', 57, 61, 59, 53],
            ['prop', 56, 62, 59, 53],
            ['prop', 55, 63, 59, 53],
            ['prop', 54, 64, 59, 53],
            ['prop', 38, 44, 59, 53],

            # 64 - 77
            ['prop', 58, 60, 57, 61],
            ['prop', 57, 61, 56, 62],
            ['prop', 56, 62, 55, 63],
            ['prop', 55, 63, 54, 64],
            ['prop', 57, 61, 31, 37], #
            ['prop', 56, 62, 31, 37], #
            ['prop', 55, 63, 31, 37], #
            ['prop', 58, 60, 31, 37], #
            ['prop', 54, 64, 31, 37], #
            ['prop', 38, 44, 31, 37],
            ['prop', 59, 53, 27, 30],
            ['prop', 51, 52, 52, 53],
            ['prop', 50, 51, 50, 53],
            ['prop', 27, 30, 27, 53],

            # 78 - 86
            ['angle', 56, 57, 58], 
            ['angle', 55, 56, 57], 
            ['angle', 54, 55, 56],
            ['angle', 53, 54, 55],
            ['angle', 64, 53, 54],
            ['angle', 63, 64, 53],
            ['angle', 62, 63, 64],
            ['angle', 61, 62, 63],
            ['angle', 60, 61, 62],

            # 87 - 95
            ['angle', 31, 29, 37], ##
            ['angle', 31, 30, 37], ##
            ['angle', 27, 30, 34],
            ['angle', 51, 52, 53],
            ['angle', 27, 30, 31],
            ['angle', 37, 30, 27],
            ['angle', 37, 50, 31],
            ['angle', 63, 53, 55],
            ['angle', 29, 30, 34],
    
#              # 78 - 86
#             ['angle', 56, 57, 58, -0.1011, -0.3078,  0.9344], 
#             ['angle', 55, 56, 57, -0.9009, -0.1629,  0.3678], 
#             ['angle', 54, 55, 56, -0.7863, -0.1348,  0.5986],
#             ['angle', 53, 54, 55, -0.3654,  0.5084,  0.7771],
#             ['angle', 64, 53, 54, -0.0262,  0.9601,  0.2719],
#             ['angle', 63, 64, 53,  0.2780,  0.6064,  0.7425],
#             ['angle', 62, 63, 64,  0.8007, -0.1164,  0.5832],
#             ['angle', 61, 62, 63,  0.9095, -0.1439,  0.3239],
#             ['angle', 60, 61, 62,  0.4377, -0.2226,  0.8568],

#             # 87 - 95
#             ['angle', 31, 29, 37, -0.0054, -0.6474,  0.7596], ##
#             ['angle', 31, 30, 37, -0.0098, -0.9611,  0.2697], ##
#             ['angle', 27, 30, 34, -0.9997, -0.0218, -0.0046],
#             ['angle', 51, 52, 53, -0.9893,  0.0432, -0.0409],
#             ['angle', 27, 30, 31, -0.7108,  0.4236,  0.5553],
#             ['angle', 37, 30, 27,  0.7083,  0.4411,  0.5448],
#             ['angle', 37, 50, 31,  0.0048,  0.2632,  0.9614],
#             ['angle', 63, 53, 55,  0.0039,  0.8142,  0.5791],
#             ['angle', 29, 30, 34, -0.9987, -0.0466,  0.0199],
    
        ]


## 3. Calculation

### 3.1 Distance

In [7]:
# my version
def get_distance(face, idx1, idx2):
    x_col = face[:, idx1]
    y_col = face[:, idx1 + num_cordinate_col]
    z_col = face[:, idx1 + 2 * num_cordinate_col]
    cordinate1 = np.stack([x_col, y_col, z_col])
    
    x_col = face[:, idx2]
    y_col = face[:, idx2 + num_cordinate_col]
    z_col = face[:, idx2 + 2 * num_cordinate_col]
    cordinate2 = np.stack([x_col, y_col, z_col])
    
    diff = cordinate2 - cordinate1
    distance = np.sqrt(np.sum(diff * diff, axis=0))
    return distance

#### 3.1.1 Test

In [18]:
print("index[10], index[14] = ", face_indices[10], face_indices[14])
# example
print(get_distance(np_face, face_indices[10], face_indices[14]))
print(get_distance(np_face, 1, 2))

index[10], index[14] =  2428 3638
[1.24339906 1.25903576 1.23164034 ... 1.22402939 1.24969587 1.25556593]
[1.56063341 1.56339715 1.57822708 ... 1.57386777 1.59456764 1.51828095]


In [33]:
# example code
def wtf_get_distance(face, idx1, idx2):
    diff = face[idx1, :] - face[idx2, :]
    distance = np.sqrt(np.sum(diff * diff))
    return distance

In [33]:
face = np.array(face)
# first user
print("First user: ",face[0])

# x
print("x = : ",face[0][1])
# y
print("y = : ",face[0][1+num_cordinate_col])
# z
print("z = : ",face[0][1+2*num_cordinate_col])

First user:  [ 1.40012000e+05  1.14210358e+00  3.02940749e-01 ... -1.14440298e+00
  2.06968585e-01 -7.20105654e-01]
x = :  1.14210357642963
y = :  1.29779936879771
z = :  0.174804212387015


In [52]:
x_col = face[:, 1]
y_col = face[:, 1+num_cordinate_col]
z_col = face[:, 1+2*num_cordinate_col]
cordinate1 = np.stack([x_col, y_col, z_col])

x_col = face[:, 2]
y_col = face[:, 2+num_cordinate_col]
z_col = face[:, 2+2*num_cordinate_col]
cordinate2 = np.stack([x_col, y_col, z_col])

print("Concatenate1 x y z: ", cordinate1)
print("Cordinate1 for user 1: ", cordinate1[:,0])
print("\n")

print("Concatenate2 x y z: ", cordinate2)
print("Cordinate2 for user 1: ", cordinate2[:,0])
# print(np.transpose(cordinate))
print("\n")

diff = cordinate2[:,0] - cordinate1[:,0]
distance = np.sqrt(np.sum(diff * diff))
distance

Concatenate1 x y z:  [[1.14210358 1.14952029 1.16859276 ... 1.18577987 1.19499615 1.22740618]
 [1.29779937 1.30963107 1.3051978  ... 1.27343685 1.29636338 1.23158716]
 [0.17480421 0.20730591 0.18707371 ... 0.1772353  0.14842035 0.23237584]]
Cordinate1 for user 1:  [1.14210358 1.29779937 0.17480421]


Concatenate2 x y z:  [[ 0.30294075  0.30028706  0.2773556  ...  0.27197065  0.28210467
   0.28448762]
 [ 0.0900863   0.12766052  0.12583716 ...  0.10358477  0.10305528
   0.19451008]
 [-0.34750942 -0.36362247 -0.36574227 ... -0.34569737 -0.38570594
  -0.35119314]]
Cordinate2 for user 1:  [ 0.30294075  0.0900863  -0.34750942]




1.5606334065096383

In [68]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a)
print(a*a)
print(np.sum(a*a, axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[ 66  93 126]


In [63]:
diff = cordinate2 - cordinate1
print(diff)
print(diff.shape)
print(diff)

distance = np.sqrt(np.sum(diff * diff, axis=0))
distance

[[-0.83916283 -0.84923323 -0.89123717 ... -0.91380922 -0.91289149
  -0.94291856]
 [-1.20771306 -1.18197055 -1.17936064 ... -1.16985208 -1.19330809
  -1.03707708]
 [-0.52231363 -0.57092838 -0.55281598 ... -0.52293267 -0.53412629
  -0.58356899]]
(3, 1078)
[[-0.83916283 -0.84923323 -0.89123717 ... -0.91380922 -0.91289149
  -0.94291856]
 [-1.20771306 -1.18197055 -1.17936064 ... -1.16985208 -1.19330809
  -1.03707708]
 [-0.52231363 -0.57092838 -0.55281598 ... -0.52293267 -0.53412629
  -0.58356899]]


array([1.56063341, 1.56339715, 1.57822708, ..., 1.57386777, 1.59456764,
       1.51828095])

### 3.2 Proportion

In [8]:
# my version
def get_proportion(target, idx1, idx2, idx3, idx4):
    dist1 = get_distance(target, idx1, idx2)
    dist2 = get_distance(target, idx3, idx4)
    return dist1 / dist2

#### 3.2.1 Test

In [77]:
# example code
def wtf_get_proportion(target, idx1, idx2, idx3, idx4):
    dist1 = get_distance(target, idx1, idx2)
    dist2 = get_distance(target, idx3, idx4)
    return dist1 / dist2

In [20]:
dist1 = get_distance(np_face, 12, 14)
dist2 = get_distance(np_face, 44, 45)
print(dist1, dist2)
print("dist1 / dist2 =\n", dist1 / dist2)
print("shape of dist1 / dist2 =\n", (dist1 / dist2).shape)

[1.14543339 1.13773428 1.1086904  ... 1.09002697 1.08876476 1.11345041] [0.90957681 0.88305985 0.84902914 ... 0.79123452 0.81195322 0.8372071 ]
dist1 / dist2 =
 [1.25930364 1.28839996 1.30583316 ... 1.37762817 1.34092054 1.32995815]
shape of dist1 / dist2 =
 (1078,)


### 3.3 Angle

In [9]:
##################### TO DO #######################
def get_angle(face, idx1, idx2, idx3):
    x_col = face[:, idx1]
    y_col = face[:, idx1 + num_cordinate_col]
    z_col = face[:, idx1 + 2 * num_cordinate_col]
    cordinate1 = np.stack([x_col, y_col, z_col])
    
    x_col = face[:, idx2]
    y_col = face[:, idx2 + num_cordinate_col]
    z_col = face[:, idx2 + 2 * num_cordinate_col]
    cordinate2 = np.stack([x_col, y_col, z_col])
    
    x_col = face[:, idx3]
    y_col = face[:, idx3 + num_cordinate_col]
    z_col = face[:, idx3 + 2 * num_cordinate_col]
    cordinate3 = np.stack([x_col, y_col, z_col])
    
    # get vector
    v12 = cordinate1 - cordinate2
    v32 = cordinate3 - cordinate2
    
    # get dot product of two coordinate
    dot_prod = np.sum(v12 * v32, axis=0)
    
    # get magnitude(distance)
    mag12 = get_distance(face, idx1, idx2);
    mag32 = get_distance(face, idx3, idx2);
    
    # get cos
    cos_ = dot_prod / mag12 / mag32
    
    # get radius
    angle = np.arccos(cos_)
    
    # convert degree
    # Basically doing angle <- angle mod 360
    ang_deg = np.degrees(angle) % 360
    return ang_deg

#### 3.3.1 Test

In [21]:
get_angle(np_face, 1, 4, 330)

array([53.39897399, 52.60659287, 53.57944039, ..., 52.37297352,
       51.92487925, 53.98918242])

In [137]:
## dot product test
a = np.array([[1,2,3,1], [3,2,1,1], [2,1,3,1]])
b = np.array([[1,1,1,1], [2,2,1,2], [3,2,1,2]])
c = np.array([[2,2,1,2],[1,1,2,1], [3,2,1,2]])
print("a = \n", a)
print("b = \n", b)
print("c = \n", c)

vab = a - b
vcb = c - b

print("vab = \n", vab)
print("vcb = \n", vcb)

# get dot product of two coordinate
dot_prod = np.sum(vab * vcb, axis=0)
print("vab * vcb =\n", vab * vcb)
print("vab dot vcb = ", dot_prod)

# get magnitude(distance)
mag_ab = np.sqrt(np.sum(vab * vab, axis=0))
mag_cb = np.sqrt(np.sum(vcb * vcb, axis=0))
print("mag_ab = ", mag_ab)
print("mag_cb = ", mag_cb)

# Get cosine value
cos = dot_prod / mag_ab / mag_cb
print("cos = ", cos)

# Get angle in radians and then convert to degrees
angle = np.arccos(cos)
print("angle = ", angle)

# Basically doing angle <- angle mod 360
ang_deg = np.degrees(angle) % 360
print("ang_deg = ", ang_deg)

a = 
 [[1 2 3 1]
 [3 2 1 1]
 [2 1 3 1]]
b = 
 [[1 1 1 1]
 [2 2 1 2]
 [3 2 1 2]]
c = 
 [[2 2 1 2]
 [1 1 2 1]
 [3 2 1 2]]
vab = 
 [[ 0  1  2  0]
 [ 1  0  0 -1]
 [-1 -1  2 -1]]
vcb = 
 [[ 1  1  0  1]
 [-1 -1  1 -1]
 [ 0  0  0  0]]
vab * vcb =
 [[ 0  1  0  0]
 [-1  0  0  1]
 [ 0  0  0  0]]
vab dot vcb =  [-1  1  0  1]
mag_ab =  [1.41421356 1.41421356 2.82842712 1.41421356]
mag_cb =  [1.41421356 1.41421356 1.         1.41421356]
cos =  [-0.5  0.5  0.   0.5]
angle =  [2.0943951  1.04719755 1.57079633 1.04719755]
ang_deg =  [120.  60.  90.  60.]


In [82]:
x_col = face[:, 1]
y_col = face[:, 1+num_cordinate_col]
z_col = face[:, 1+2*num_cordinate_col]
cordinate1 = np.stack([x_col, y_col, z_col])

x_col = face[:, 2]
y_col = face[:, 2+num_cordinate_col]
z_col = face[:, 2+2*num_cordinate_col]
cordinate2 = np.stack([x_col, y_col, z_col])

print("Concatenate1 x y z: ", cordinate1)
print("Cordinate1 for user 1: ", cordinate1[:,0])
print("\n")

print("Concatenate2 x y z: ", cordinate2)
print("Cordinate2 for user 1: ", cordinate2[:,0])
# print(np.transpose(cordinate))
print("\n")

Concatenate1 x y z:  [[1.14210358 1.14952029 1.16859276 ... 1.18577987 1.19499615 1.22740618]
 [1.29779937 1.30963107 1.3051978  ... 1.27343685 1.29636338 1.23158716]
 [0.17480421 0.20730591 0.18707371 ... 0.1772353  0.14842035 0.23237584]]
Cordinate1 for user 1:  [1.14210358 1.29779937 0.17480421]


Concatenate2 x y z:  [[ 0.30294075  0.30028706  0.2773556  ...  0.27197065  0.28210467
   0.28448762]
 [ 0.0900863   0.12766052  0.12583716 ...  0.10358477  0.10305528
   0.19451008]
 [-0.34750942 -0.36362247 -0.36574227 ... -0.34569737 -0.38570594
  -0.35119314]]
Cordinate2 for user 1:  [ 0.30294075  0.0900863  -0.34750942]




## 4. Measurement and AM DataFrame

In [10]:
def get_measurement(face, info):
    mtype = info[0]
    idx1 = face_indices[info[1]]
    idx2 = face_indices[info[2]]
    if mtype == 'dist':
        measurement = get_distance(face, idx1, idx2)
    elif mtype == 'prop':
        idx3 = face_indices[info[3]]
        idx4 = face_indices[info[4]]
        measurement = get_proportion(face, idx1, idx2, idx3, idx4)
    elif mtype == 'angle':
        idx3 = face_indices[info[3]]
        measurement = get_angle(face, idx1, idx2, idx3)
    else:
        raise ValueError('unknown type {}'.format(mtype))

    return measurement

In [17]:
# form the new csv of AM column
AM_Unnormalized = []
AM_OG = []

np_face = np.array(face)
for info in measurement_info:
    new_AM_col = get_measurement(np_face, info)
    AM_Unnormalized.append(new_AM_col)
AM_Unnormalized_df = pd.DataFrame(AM_Unnormalized).T
# Column start from 1
AM_Unnormalized_df.columns += 1
AM_OG = pd.DataFrame.copy(AM_Unnormalized_df)

# Insert ID back
AM_Unnormalized_df.insert(0, "ID", face["ID"])
AM_Unnormalized_df

ID         1         2         3         4         5         6  \
0     140012  1.243399  0.897036  0.759408  1.419205  1.148332  1.161105   
1     140017  1.259036  0.912938  0.763635  1.438525  1.102955  1.141477   
2     140018  1.231640  0.920481  0.790598  1.401998  1.110782  1.120131   
3     140019  1.256924  0.919224  0.705850  1.476768  1.146594  1.177854   
4     140020  1.195197  0.900752  0.792212  1.375182  1.131484  1.151429   
...      ...       ...       ...       ...       ...       ...       ...   
1073  143771  1.220739  0.889086  0.777694  1.385133  1.118757  1.137757   
1074  143772  1.229232  0.936953  0.791519  1.424546  1.136169  1.149582   
1075  143773  1.224029  0.929952  0.799422  1.413355  1.101050  1.145108   
1076  143774  1.249696  0.943250  0.830836  1.417172  1.085187  1.090428   
1077  143775  1.255566  0.976129  0.809726  1.445739  1.090970  1.119886   

             7         8         9  ...         87         88         89  \
0     0.738964  1.516626  1.253521  ...  58.804049  27.414642   9.930506   
1     0.760508  1.513170  1.282743  ...  58.474637  28.989447  10.517957   
2     0.745486  1.509870  1.271416  ...  56.498925  24.139417   9.593009   
3     0.788291  1.550072  1.288071  ...  60.605922  32.818543  10.682783   
4     0.761942  1.478946  1.227277  ...  58.232696  26.547720  10.334075   
...        ...       ...       ...  ...        ...        ...        ...   
1073  0.798562  1.487507  1.336559  ...  55.971474  29.609547  11.610561   
1074  0.748178  1.498560  1.246664  ...  57.159285  26.145503  10.428154   
1075  0.719819  1.462087  1.257362  ...  56.564373  28.453503  12.170909   
1076  0.747315  1.500895  1.302947  ...  56.507516  26.367264  10.455140   
1077  0.721119  1.493011  1.259050  ...  55.495787  25.616678   9.773500   

             90         91         92         93         94         95  \
0     65.297325  45.118798  64.132135  54.896465  29.862477  25.268476   
1     65.236893  43.785196  63.742448  55.004201  29.898430  27.042034   
2     64.757623  43.262276  63.281389  55.064633  21.198106  24.631410   
3     64.521880  47.095292  63.119774  54.163523  36.932913  24.946419   
4     66.579356  45.446894  65.487251  55.398140  29.941617  24.095442   
...         ...        ...        ...        ...        ...        ...   
1073  67.081279  43.174409  65.929989  54.945651  27.194088  26.884777   
1074  65.382626  42.981064  64.239122  55.279869  24.029696  25.784772   
1075  66.530021  40.501347  65.026592  54.933875  18.654140  27.931111   
1076  65.775786  42.440195  64.427415  54.763247  23.437985  26.303192   
1077  63.039461  43.816024  61.660115  54.208468  23.822106  27.728496   

             96  
0     26.370851  
1     27.259169  
2     26.511657  
3     27.789455  
4     26.448005  
...         ...  
1073  27.060903  
1074  27.499367  
1075  28.307838  
1076  25.722799  
1077  26.575883  

[1078 rows x 97 columns]

In [22]:
# Export csv
AM_Unnormalized_df.to_csv("./AMs_unnormalized.csv", index=False)

### 4.1 Test

In [155]:
print("measurement_info:", measurement_info[0])
print("measurement_info:", measurement_info[67])
print("measurement_info:", measurement_info[90])

measurement_info: ['dist', 10, 14]
measurement_info: ['prop', 55, 63, 54, 64]
measurement_info: ['angle', 51, 52, 53]


In [156]:
get_measurement(face, measurement_info[0])

array([1.24339906, 1.25903576, 1.23164034, ..., 1.22402939, 1.24969587,
       1.25556593])

## 5. Normalization

In [19]:
AM_mean = AM_OG.mean()
AM_std  = AM_OG.std()
# Standard 
AM_df = (AM_OG - AM_mean) / AM_std
# add ID back
face = pd.read_csv('./penstate_data/download/qls.csv')
AM_df.insert(0, "ID", face["ID"])
AM_df

ID         1         2         3         4         5         6  \
0     140012  0.979992 -1.466816 -0.831445  0.163257  1.186042  0.748534   
1     140017  1.664156 -0.801666 -0.701065  0.869178 -0.793944 -0.085106   
2     140018  0.465505 -0.486156  0.130590 -0.465439 -0.452386 -0.991666   
3     140019  1.571772 -0.538745 -2.483406  2.266499  1.110213  1.459845   
4     140020 -1.129009 -1.311359  0.180367 -1.445244  0.450922  0.337577   
...      ...       ...       ...       ...       ...       ...       ...   
1073  143771 -0.011469 -1.799327 -0.267434 -1.081637 -0.104433 -0.243079   
1074  143772  0.360120  0.202809  0.158976  0.358438  0.655343  0.259119   
1075  143773  0.132498 -0.090021  0.402741 -0.050488 -0.877057  0.069140   
1076  143774  1.255501  0.466187  1.371687  0.088982 -1.569201 -2.253172   
1077  143775  1.512338  1.841444  0.720577  1.132770 -1.316902 -1.002074   

             7         8         9  ...        87        88        89  \
0    -0.812294  0.285578 -0.946772  ...  1.184660 -0.355536 -1.357817   
1     0.252811  0.163068  0.242396  ...  0.923665  0.231939 -0.541167   
2    -0.489832  0.046085 -0.218536  ... -0.641710 -1.577346 -1.826992   
3     1.626359  1.471079  0.459243  ...  2.612300  1.660369 -0.312034   
4     0.323690 -1.050004 -2.014781  ...  0.731973 -0.678938 -0.796792   
...        ...       ...       ...  ...       ...       ...       ...   
1073  2.134127 -0.746575  2.432453  ... -1.059613  0.463265  0.977725   
1074 -0.356755 -0.354786 -1.225821  ... -0.118500 -0.828984 -0.666008   
1075 -1.758782 -1.647611 -0.790459  ... -0.589854  0.032007  1.756697   
1076 -0.399454 -0.272028  1.064594  ... -0.634902 -0.746256 -0.628493   
1077 -1.694526 -0.551474 -0.721777  ... -1.436504 -1.026260 -1.576080   

            90        91        92        93        94        95        96  
0    -0.429220  1.006778 -0.293894 -0.183394  0.837010 -0.603628 -0.983879  
1    -0.480632 -0.040503 -0.584514 -0.016203  0.846367  0.561269  0.066214  
2    -0.888363 -0.451153 -0.928363  0.077580 -1.417918 -1.022061 -0.817431  
3    -1.088919  2.558924 -1.048892 -1.320823  2.677112 -0.815159  0.693073  
4     0.661450  1.264433  0.716723  0.595138  0.857607 -1.374092 -0.892674  
...        ...       ...       ...       ...       ...       ...       ...  
1073  1.088453 -0.520156  1.046909 -0.107065  0.142554  0.457980 -0.168159  
1074 -0.356651 -0.671990 -0.214105  0.411597 -0.680988 -0.264517  0.350156  
1075  0.619479 -2.619318  0.373174 -0.125339 -2.079993  1.145226  1.305862  
1076 -0.022176 -1.096736 -0.073680 -0.390131 -0.834983  0.075987 -1.749951  
1077 -2.350065 -0.016294 -2.137475 -1.251074 -0.735014  1.012146 -0.741508  

[1078 rows x 97 columns]

In [20]:
# Export csv
AM_df.to_csv("./AMs_final.csv", index=False)

###### 5.1 Test

In [109]:
AM_Unnormalized_df.mean()

0     0.635724
1     0.832036
2     0.462624
3     1.005137
4     1.059509
        ...   
91    0.875191
92    0.183650
93    0.602348
94    0.986343
95    0.153147
Length: 96, dtype: float64